INSERT INTO Especialidades (nome) VALUES 
('Cardiologia'),('Dermatologia'),('Pediatria'),('Ortopedia'),('Ginecologia');

INSERT INTO Clinicas (nome, cidade) VALUES
('Clinica Central', 'São Paulo'),
('Clinica Vida', 'Rio de Janeiro'),
('Clinica Bem Estar', 'Belo Horizonte'),
('Clinica Saúde+', 'Curitiba'),
('Clinica Saúde Total', 'Porto Alegre'),
('Clínica Mineira', 'Belo Horizonte'),
('Centro Médico Paulista', 'São Paulo'),
('Clínica Copacabana', 'Rio de Janeiro'),
('Clínica Pinhais', 'Curitiba'),
('Saúde POA Platinum', 'Porto Alegre'),
('Atendimento Clínico SP', 'São Paulo'),
('Saúde RJ Premium', 'Rio de Janeiro'),
('Clínica Savassi', 'Belo Horizonte'),
('Clínica Auxiliadora', 'Porto Alegre'),
('Clínica Jardim América', 'São Paulo'),
('Atendimento Vital', 'Rio de Janeiro'),
('Saúde Curitiba Max', 'Curitiba'),
('Saúde BH Excellence', 'Belo Horizonte'),
('Clínica Salvador', 'Salvador'),
('Clínica Leblon', 'Rio de Janeiro'),
('Bem Viver SP', 'São Paulo'),
('Clínica Batel', 'Curitiba'),
('Clínica Moinhos de Vento', 'Porto Alegre'),
('Clínica Paulista', 'São Paulo'),
('Clínica Ipanema', 'Rio de Janeiro'),
('Centro Médico Minas', 'Belo Horizonte'),
('Clínica Recife', 'Recife'),
('Clínica Morumbi', 'São Paulo'),
('Saúde Total RJ', 'Rio de Janeiro'),
('Clínica Pampulha', 'Belo Horizonte'),
('Clínica Reabilita', 'Curitiba'),
('Clínica Gaúcha', 'Porto Alegre'),
('Serviços Médicos Zona Sul', 'São Paulo'),
('Bem Estar da Gávea', 'Rio de Janeiro'),
('Bem Estar BH', 'Belo Horizonte'),
('Centro Médico Paraná', 'Curitiba'),
('Centro de Especialidades Sul', 'Porto Alegre'),
('Consultórios Brooklin', 'São Paulo'),
('Clínica Barra', 'Rio de Janeiro'),
('Serviços de Saúde MG', 'Belo Horizonte'),
('Clínica Saúde & Cuidado', 'Curitiba'),
('Bem Estar POA', 'Porto Alegre'),
('Clínica Esperança', 'São Paulo'),
('Consultórios Tijuca', 'Rio de Janeiro'),
('Clínica Horizonte', 'Belo Horizonte'),
('Clínica Fortaleza', 'Fortaleza'),
('Clínica Alpha', 'São Paulo'),
('Clínica Zênite', 'Rio de Janeiro'),
('Consultórios Centro BH', 'Belo Horizonte'),
('Bem Viver Curitiba', 'Curitiba'),
('Serviços Médicos RS', 'Porto Alegre'),
('Clínica Beta', 'São Paulo'),
('Clínica Ómega', 'Rio de Janeiro'),
('Clínica Alfa BH', 'Belo Horizonte'),
('Clínica Brasília', 'Brasília'),
('Consultórios Juvevê', 'Curitiba'),
('Clínica Gama', 'São Paulo'),
('Clínica Sigma', 'Rio de Janeiro'),
('Clínica Saúde Forte', 'Belo Horizonte'),
('Clínica Sul Saúde', 'Curitiba'),
('Consultórios Independência', 'Porto Alegre'),
('Clínica Manaus', 'Manaus'),
('Clínica Delta', 'São Paulo'),
('Clínica Teta', 'Rio de Janeiro'),
('Clínica Harmonia', 'Belo Horizonte'),
('Clínica Fênix', 'Curitiba'),
('Clínica Vida Nova', 'Porto Alegre'),
('Clínica Belém', 'Belém'),
('Clínica Epsilon', 'São Paulo'),
('Clínica Goiânia', 'Goiânia'),
('Clínica Ametista', 'Curitiba'),
('Clínica Estrela', 'Porto Alegre'),
('Clínica Campinas', 'Campinas'),
('Clínica São Luís', 'São Luís'),
('Clínica Natal', 'Natal'),
('Clínica Teresina', 'Teresina'),
('Clínica João Pessoa', 'João Pessoa'),
('Clínica Campo Grande', 'Campo Grande'),
('Clínica Maceió', 'Maceió'),
('Clínica Cuiabá', 'Cuiabá'),
('Clínica Florianópolis', 'Florianópolis'),
('Clínica Vitória', 'Vitória'),
('Clínica Aracaju', 'Aracaju'),
('Clínica Palmas', 'Palmas'),
('Clínica Safira', 'Curitiba'),
('Clínica Rubi', 'Porto Alegre'),
('Clínica Esmeralda', 'Porto Alegre'),
('Clínica Ribeirão', 'Ribeirão Preto'),
('Clínica Uberlândia', 'Uberlândia'),
('Clínica Sorocaba', 'Sorocaba'),
('Clínica Osasco', 'Osasco'),
('Clínica Contagem', 'Contagem'),
('Clínica Jundiaí', 'Jundiaí'),
('Clínica Canoas', 'Canoas');

INSERT INTO Medicos (CRM, nome, especialidade_ID, clinica_ID) VALUES
(12345,'Dr. João',1,1),
(12346,'Dra. Maria',2,2),
(12347,'Dr. Pedro',3,3),
(12348,'Dra. Ana',4,4),
(12349,'Dr. Carlos',5,5);

INSERT INTO Pacientes (nome, cpf, telefone, dataNasc, cidade) VALUES
('Lucas Silva','111.111.111-11','(11)11111-1111','1995-05-10','São Paulo'),
('Maria Souza','222.222.222-22','(21)22222-2222','2000-03-15','Rio de Janeiro'),
('Pedro Lima','333.333.333-33','(31)33333-3333','1988-12-20','Belo Horizonte'),
('Ana Costa','444.444.444-44','(41)44444-4444','1992-08-05','Curitiba'),
('Carla Mendes','555.555.555-55','(51)55555-5555','1999-07-22','Porto Alegre');

INSERT INTO Consultas (paciente_ID, medico_ID, dataConsulta, status) VALUES
(1,1,'2025-10-01 10:00:00','Agendada'),
(2,2,'2025-10-02 11:00:00','Agendada'),
(3,3,'2025-10-03 09:00:00','Agendada'),
(4,4,'2025-10-04 14:00:00','Agendada'),
(5,5,'2025-10-05 15:00:00','Agendada');


UPDATE Pacientes
SET telefone = '(11)99999-9999'
WHERE paciente_ID = 1;

DELETE FROM Consultas
WHERE consulta_ID = 10 AND status = 'Cancelada';


